# fly.toml app configuration file generated for polyprophet on 2026-05-03T11:26:34Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'polyprophet'
primary_region = 'gru'

[build]
  dockerfile = 'Dockerfile'

[env]
  CLOB_FORCE_PROXY = '0'
  DEFAULT_MIN_ORDER_SHARES = '5'
  ENABLE_LIVE_TRADING = 'true'
  HARD_ENTRY_PRICE_CAP = '0.82'
  LIVE_AUTOTRADING_ENABLED = 'false'
  MAX_GLOBAL_TRADES_PER_CYCLE = '1'
  MULTIFRAME_4H_ENABLED = 'false'
  NODE_ENV = 'production'
  OPERATOR_STAKE_FRACTION = '0.25'
  POLYMARKET_AUTO_DERIVE_CREDS = 'true'
  TELEGRAM_FLY_SECRETS_ENABLED = 'true'
  TELEGRAM_FLY_APP_NAME = 'polyprophet'
  POLYMARKET_SIGNATURE_TYPE = '1'
  PORT = '8080'
  REQUIRE_REAL_ORDERBOOK = 'true'
  START_PAUSED = 'true'
  STRATEGY_SET_15M_PATH = 'strategies/strategy_set_15m_epoch3v2_portfolio.json'
  TIMEFRAME_15M_ENABLED = 'true'
  TIMEFRAME_15M_MIN_BANKROLL = '3'
  TIMEFRAME_5M_ENABLED = 'false'
  TRADE_MODE = 'LIVE'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'off'
  auto_start_machines = true
  min_machines_running = 1

  [http_service.concurrency]
    type = 'connections'
    hard_limit = 100
    soft_limit = 80

[[vm]]
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024
